import { describe, it, expect } from "bun:test";
import { sha256 } from "@noble/hashes/sha2.js";
import {
  computeBoundParamsHash,
  computeStealthDataHash,
  createTransferBoundParams,
  createUnshieldBoundParams,
  createSuiUnshieldBoundParams,
  createRedeemBoundParams,
  computeSuiTransferBoundParamsHash,
  computeSuiUnshieldBoundParamsHash,
  computeSuiRedeemBoundParamsHash,
} from "../../src/bound-params";
import { poseidonHashSync, reduceToField } from "../../src/poseidon";
import { bigintTo32Bytes } from "../../src/instructions";

/**
 * Sui length-prefixed bound-params parity (audit #4 / #51–54). These 32-byte BE field
 * elements MUST equal the on-chain Move outputs, locked in:
 *   token_registry_tests::unshield_hash_matches_sdk_vector
 *   transact_tests::transfer_hash_matches_sdk_vector
 *   (redeem) bound_params length-prefixed encoding
 */
describe("Sui length-prefixed bound-params (Move parity)", () => {
  const beHex = (v: bigint) => v.toString(16).padStart(64, "0");
  const addr32 = (hex: string) => {
    const clean = hex.replace(/^0x/, "").padStart(64, "0");
    const out = new Uint8Array(32);
    for (let i = 0; i < 32; i++) out[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16);
    return out;
  };

  it("transfer hash matches Move (stealth=[72×0x11])", () => {
    const got = computeSuiTransferBoundParamsHash([new Uint8Array(72).fill(0x11)]);
    expect(beHex(got)).toBe("089f78cb332df8a2af8c34e4bf4c8477daf60a38dd6eddd43b6161c4ff8ad9da");
  });

  it("unshield hash matches Move (recipients=[0xA11CE,0xB0B], stealth=[72×0x11])", () => {
    const got = computeSuiUnshieldBoundParamsHash(
      [addr32("A11CE"), addr32("B0B")],
      [new Uint8Array(72).fill(0x11)],
    );
    expect(beHex(got)).toBe("25f18c980939dfacb79f4159fed02f10537abf0608d334c5d29dd9a9e3d5f3a5");
  });

  it("redeem hash matches Move (scripts=[34×0x51], stealth=[])", () => {
    const got = computeSuiRedeemBoundParamsHash([new Uint8Array(34).fill(0x51)], []);
    expect(beHex(got)).toBe("2f145c70b95e405aea4f325aed69eadb63a2a042f2c297c4a581c93fb6ce3dbb");
  });

  it("different script partitioning yields a different hash (the #4 fix)", () => {
    // [AB] vs [A,B] with the same concatenated bytes must now differ.
    const concat = computeSuiRedeemBoundParamsHash([new Uint8Array([0x51, 0x52, 0x53, 0x54])], []);
    const split = computeSuiRedeemBoundParamsHash(
      [new Uint8Array([0x51, 0x52]), new Uint8Array([0x53, 0x54])],
      [],
    );
    expect(beHex(concat)).not.toBe(beHex(split));
  });
});

/**
 * Cross-language parity tests — these test vectors must produce identical
 * results in both TypeScript (SDK) and Rust (on-chain program).
 *
 * Rust vectors generated by: cargo test -- test_bound_params_cross_lang_vectors --nocapture
 *
 * NOTE: unshield vectors changed in the multi-output migration because
 * unshieldAddress is now SHA256(concat(owners)) instead of raw owner bytes.
 * Transfer and redeem (single script) vectors are unchanged.
 */
describe("boundParamsHash cross-language parity", () => {
  const CHAIN_ID = 103n;
  const ZERO_STEALTH = new Uint8Array(32);
  // Fixed requester for redeem cross-layer vectors (mirrors the Rust test).
  const REQ = new Uint8Array(32).fill(0xDD);

  it("transfer: chain_id=103, zero stealth", () => {
    const params = createTransferBoundParams(ZERO_STEALTH, CHAIN_ID);
    const hash = computeBoundParamsHash(params);
    const hashBytes = bigintTo32Bytes(hash);
    const hashHex = Array.from(hashBytes).map(b => b.toString(16).padStart(2, "0")).join("");

    // Must match Rust VECTOR_transfer (unchanged)
    expect(hashHex).toBe("06db1d31bd2ae34ed282aa200e61b183b67320420360c035d947c5263a21794d");
  });

  it("transfer: Sui chain_id=784, stealth=0x11*72 — matches Move transfer_hash", () => {
    const stealth = new Uint8Array(72).fill(0x11);
    const params = createTransferBoundParams(computeStealthDataHash([stealth]), 784n);
    const hash = computeBoundParamsHash(params);
    const hashHex = Array.from(bigintTo32Bytes(hash)).map(b => b.toString(16).padStart(2, "0")).join("");
    // Pinned in sui-programs transact_tests::transfer_hash_matches_sdk_vector
    expect(hashHex).toBe("00255687330aa6944333062dde58aef6c29c08f718af38804ab99d4616ada196");
  });

  it("sui unshield_hash + sui_token_id: matches Move token_registry_tests vectors", () => {
    // Two test recipients as 32-byte big-endian Sui addresses (@0xA11CE, @0xB0B).
    const suiAddr = (hex: string): Uint8Array => {
      const out = new Uint8Array(32);
      const h = hex.replace(/^0x/, "").padStart(64, "0");
      for (let i = 0; i < 32; i++) out[i] = Number.parseInt(h.slice(i * 2, i * 2 + 2), 16);
      return out;
    };
    const recipients = [suiAddr("A11CE"), suiAddr("B0B")];
    const stealth = new Uint8Array(72).fill(0x11);
    const stealthHash = computeStealthDataHash([stealth]);

    const params = createSuiUnshieldBoundParams(recipients, stealthHash);
    const hashHex = Array.from(bigintTo32Bytes(computeBoundParamsHash(params)))
      .map((b) => b.toString(16).padStart(2, "0")).join("");
    // Pinned in token_registry_tests::unshield_hash_matches_sdk_vector
    expect(hashHex).toBe("07409ca23f284d6ce3cb9b26a898564117faa88a6dd496f926e1c340dd748b35");

    // sui_token_id<SUI> = poseidon(reduce_to_field(sha2_256(typeName)), 0).
    // typeName is the on-chain `type_name::get<SUI>().into_string()` for the test type.
    const typeName =
      "a5a0ff39f17b1eec14742c58a605257af9cbc677c5541cd63f103c6a09796cd8::token_registry_tests::SUI";
    const tokenId = poseidonHashSync([reduceToField(sha256(new TextEncoder().encode(typeName))), 0n]);
    // Pinned in token_registry_tests::sui_token_id_matches_sdk_vector
    expect("0x" + tokenId.toString(16)).toBe(
      "0xe94827c457076803d7e193e2c2a5c9cc9efcedf973cb850ca8452527840ea5d",
    );
  });

  it("unshield: chain_id=103, address=0xAA*32, zero stealth (multi-output format)", () => {
    const addr = new Uint8Array(32).fill(0xAA);
    // Now uses SHA256(addr) as destinations_hash (was raw addr before)
    const params = createUnshieldBoundParams(addr, ZERO_STEALTH, CHAIN_ID);
    const hash = computeBoundParamsHash(params);
    const hashBytes = bigintTo32Bytes(hash);
    const hashHex = Array.from(hashBytes).map(b => b.toString(16).padStart(2, "0")).join("");

    // Must match Rust VECTOR_unshield (regenerated for multi-output: SHA256(owner) format)
    expect(hashHex).toBe("0d9a935c0e397e121313f4aaebdda5f5da92ba4dd6daae85e6934a150d97dd0f");
  });

  it("redeem: chain_id=103, btcScript=5120+0xBB*32, zero stealth, requester=0xDD*32", () => {
    const script = new Uint8Array(34);
    script[0] = 0x51;
    script[1] = 0x20;
    script.fill(0xBB, 2);
    const params = createRedeemBoundParams(script, ZERO_STEALTH, REQ, CHAIN_ID);
    const hash = computeBoundParamsHash(params);
    const hashBytes = bigintTo32Bytes(hash);
    const hashHex = Array.from(hashBytes).map(b => b.toString(16).padStart(2, "0")).join("");

    // Cross-layer vector — must equal compute_bound_params_hash_redeem on-chain
    // (Rust test: redeem_bound_params_binds_requester). Changed for audit #4:
    // scripts are now length-prefixed (count + per-script length) before hashing.
    expect(hashHex).toBe("2bd645748800b0c1d5ba5c25fb9ea6bab8e018686d4e215b3c9b5b5905304121");
  });

  it("transfer with non-zero stealth: chain_id=103, stealth=0xCC*32", () => {
    const stealthNz = new Uint8Array(32).fill(0xCC);
    const params = createTransferBoundParams(stealthNz, CHAIN_ID);
    const hash = computeBoundParamsHash(params);
    const hashBytes = bigintTo32Bytes(hash);
    const hashHex = Array.from(hashBytes).map(b => b.toString(16).padStart(2, "0")).join("");

    // Must match Rust VECTOR_transfer_nz (unchanged)
    expect(hashHex).toBe("22de1a31d6fa3eafa4d52d4898c6318aef2fe57e55c117c2ecf9dcffba6cb963");
  });

  it("multi-output unshield: two recipients produce different hash than single", () => {
    const addr1 = new Uint8Array(32).fill(0xAA);
    const addr2 = new Uint8Array(32).fill(0xBB);
    const singleHash = computeBoundParamsHash(
      createUnshieldBoundParams(addr1, ZERO_STEALTH, CHAIN_ID)
    );
    const multiHash = computeBoundParamsHash(
      createUnshieldBoundParams([addr1, addr2], ZERO_STEALTH, CHAIN_ID)
    );
    expect(singleHash).not.toBe(multiHash);
  });

  it("multi-output redeem: two scripts produce different hash than single", () => {
    const script1 = new Uint8Array([0x51, 0x20, 0xAA, 0xBB]);
    const script2 = new Uint8Array([0x51, 0x20, 0xCC, 0xDD]);
    const singleHash = computeBoundParamsHash(
      createRedeemBoundParams(script1, ZERO_STEALTH, REQ, CHAIN_ID)
    );
    const multiHash = computeBoundParamsHash(
      createRedeemBoundParams([script1, script2], ZERO_STEALTH, REQ, CHAIN_ID)
    );
    expect(singleHash).not.toBe(multiHash);
  });
});

describe("computeStealthDataHash", () => {
  it("returns SHA256 of empty for empty array", () => {
    const hash = computeStealthDataHash([]);
    // SHA256("") = e3b0c442...
    expect(hash[0]).toBe(0xe3);
    expect(hash.length).toBe(32);
    // NOT all zeros — must match on-chain sha256(empty_slice)
    expect(hash).not.toEqual(new Uint8Array(32));
  });

  it("produces deterministic output", () => {
    const sd1 = new Uint8Array(72).fill(0xAA);
    const sd2 = new Uint8Array(72).fill(0xBB);
    const hash1 = computeStealthDataHash([sd1, sd2]);
    const hash2 = computeStealthDataHash([sd1, sd2]);
    expect(hash1).toEqual(hash2);
  });

  it("different data produces different hashes", () => {
    const sd1 = new Uint8Array(72).fill(0xAA);
    const sd2 = new Uint8Array(72).fill(0xBB);
    const hashA = computeStealthDataHash([sd1]);
    const hashB = computeStealthDataHash([sd2]);
    expect(hashA).not.toEqual(hashB);
  });
});

describe("boundParamsHash properties", () => {
  const STEALTH = new Uint8Array(32);
  const REQ = new Uint8Array(32).fill(0xDD);

  it("different modes produce different hashes", () => {
    const transfer = computeBoundParamsHash(createTransferBoundParams(STEALTH));
    const unshield = computeBoundParamsHash(
      createUnshieldBoundParams(new Uint8Array(32), STEALTH)
    );
    const redeem = computeBoundParamsHash(
      createRedeemBoundParams(new Uint8Array([0x51, 0x20]), STEALTH, REQ)
    );
    expect(transfer).not.toBe(unshield);
    expect(transfer).not.toBe(redeem);
    expect(unshield).not.toBe(redeem);
  });

  it("different stealth data produces different hashes", () => {
    const stealthA = new Uint8Array(32).fill(0x11);
    const stealthB = new Uint8Array(32).fill(0x22);
    const hashA = computeBoundParamsHash(createTransferBoundParams(stealthA));
    const hashB = computeBoundParamsHash(createTransferBoundParams(stealthB));
    expect(hashA).not.toBe(hashB);
  });

  it("different btcScript produces different redeem hashes", () => {
    const stealth = new Uint8Array(32);
    const scriptA = new Uint8Array([0x51, 0x20, 0xAA]);
    const scriptB = new Uint8Array([0x51, 0x20, 0xBB]);
    const hashA = computeBoundParamsHash(createRedeemBoundParams(scriptA, stealth, REQ));
    const hashB = computeBoundParamsHash(createRedeemBoundParams(scriptB, stealth, REQ));
    expect(hashA).not.toBe(hashB);
  });
});
