import { describe, it, expect } from "bun:test";
import { sha256 } from "@noble/hashes/sha2.js";
import {
  computeBoundParamsHash,
  computeSolanaDomainBoundParamsHash,
  computeSolanaDomainSeparator,
  computeStealthDataHash,
  createTransferBoundParams,
  createUnshieldBoundParams,
  createRedeemBoundParams,
} from "../../src/bound-params";
import { bigintTo32Bytes } from "../../src/instructions";

/**
 * Cross-language parity tests — these test vectors must produce identical
 * results in both TypeScript (SDK) and Rust (on-chain program).
 *
 * Rust vectors generated by: cargo test -- test_bound_params_cross_lang_vectors --nocapture
 *
 * NOTE: unshield vectors changed in the multi-output migration because
 * unshieldAddress is now SHA256(concat(owners)) instead of raw owner bytes.
 * Transfer and redeem (single script) vectors are unchanged.
 */
describe("boundParamsHash cross-language parity", () => {
  const CHAIN_ID = 103n;
  const ZERO_STEALTH = new Uint8Array(32);
  // Fixed requester for redeem cross-layer vectors (mirrors the Rust test).
  const REQ = new Uint8Array(32).fill(0xDD);

  it("transfer: chain_id=103, zero stealth", () => {
    const params = createTransferBoundParams(ZERO_STEALTH, CHAIN_ID);
    const hash = computeBoundParamsHash(params);
    const hashBytes = bigintTo32Bytes(hash);
    const hashHex = Array.from(hashBytes).map(b => b.toString(16).padStart(2, "0")).join("");

    // Must match Rust VECTOR_transfer (unchanged)
    expect(hashHex).toBe("06db1d31bd2ae34ed282aa200e61b183b67320420360c035d947c5263a21794d");
  });

  it("unshield: chain_id=103, address=0xAA*32, zero stealth (multi-output format)", () => {
    const addr = new Uint8Array(32).fill(0xAA);
    // Now uses SHA256(addr) as destinations_hash (was raw addr before)
    const params = createUnshieldBoundParams(addr, ZERO_STEALTH, CHAIN_ID);
    const hash = computeBoundParamsHash(params);
    const hashBytes = bigintTo32Bytes(hash);
    const hashHex = Array.from(hashBytes).map(b => b.toString(16).padStart(2, "0")).join("");

    // Must match Rust VECTOR_unshield (regenerated for multi-output: SHA256(owner) format)
    expect(hashHex).toBe("0d9a935c0e397e121313f4aaebdda5f5da92ba4dd6daae85e6934a150d97dd0f");
  });

  it("redeem: chain_id=103, btcScript=5120+0xBB*32, zero stealth, requester=0xDD*32", () => {
    const script = new Uint8Array(34);
    script[0] = 0x51;
    script[1] = 0x20;
    script.fill(0xBB, 2);
    const params = createRedeemBoundParams(script, ZERO_STEALTH, REQ, CHAIN_ID);
    const hash = computeBoundParamsHash(params);
    const hashBytes = bigintTo32Bytes(hash);
    const hashHex = Array.from(hashBytes).map(b => b.toString(16).padStart(2, "0")).join("");

    // Cross-layer vector — must equal compute_bound_params_hash_redeem on-chain
    // (Rust test: redeem_bound_params_binds_requester). Changed for audit #4:
    // scripts are now length-prefixed (count + per-script length) before hashing.
    expect(hashHex).toBe("2bd645748800b0c1d5ba5c25fb9ea6bab8e018686d4e215b3c9b5b5905304121");
  });

  it("transfer with non-zero stealth: chain_id=103, stealth=0xCC*32", () => {
    const stealthNz = new Uint8Array(32).fill(0xCC);
    const params = createTransferBoundParams(stealthNz, CHAIN_ID);
    const hash = computeBoundParamsHash(params);
    const hashBytes = bigintTo32Bytes(hash);
    const hashHex = Array.from(hashBytes).map(b => b.toString(16).padStart(2, "0")).join("");

    // Must match Rust VECTOR_transfer_nz (unchanged)
    expect(hashHex).toBe("22de1a31d6fa3eafa4d52d4898c6318aef2fe57e55c117c2ecf9dcffba6cb963");
  });

  it("multi-output unshield: two recipients produce different hash than single", () => {
    const addr1 = new Uint8Array(32).fill(0xAA);
    const addr2 = new Uint8Array(32).fill(0xBB);
    const singleHash = computeBoundParamsHash(
      createUnshieldBoundParams(addr1, ZERO_STEALTH, CHAIN_ID)
    );
    const multiHash = computeBoundParamsHash(
      createUnshieldBoundParams([addr1, addr2], ZERO_STEALTH, CHAIN_ID)
    );
    expect(singleHash).not.toBe(multiHash);
  });

  it("multi-output redeem: two scripts produce different hash than single", () => {
    const script1 = new Uint8Array([0x51, 0x20, 0xAA, 0xBB]);
    const script2 = new Uint8Array([0x51, 0x20, 0xCC, 0xDD]);
    const singleHash = computeBoundParamsHash(
      createRedeemBoundParams(script1, ZERO_STEALTH, REQ, CHAIN_ID)
    );
    const multiHash = computeBoundParamsHash(
      createRedeemBoundParams([script1, script2], ZERO_STEALTH, REQ, CHAIN_ID)
    );
    expect(singleHash).not.toBe(multiHash);
  });
});

describe("Solana privacy-domain binding", () => {
  const PROGRAM = new Uint8Array(32).fill(0x11);
  const POOL = new Uint8Array(32).fill(0x22);
  const PARAMS = createTransferBoundParams(new Uint8Array(32), 103n);

  it("binds the existing public input to public versus institution", () => {
    const publicContext = { programId: PROGRAM, poolState: POOL, kind: "public" } as const;
    const institutionContext = {
      programId: PROGRAM,
      poolState: POOL,
      kind: "institution",
    } as const;

    expect(computeSolanaDomainSeparator(publicContext)).not.toBe(
      computeSolanaDomainSeparator(institutionContext),
    );
    expect(computeSolanaDomainBoundParamsHash(PARAMS, publicContext)).not.toBe(
      computeSolanaDomainBoundParamsHash(PARAMS, institutionContext),
    );
  });

  it("changes when the program or pool identity changes", () => {
    const base = { programId: PROGRAM, poolState: POOL, kind: "public" } as const;
    const otherProgram = {
      ...base,
      programId: new Uint8Array(32).fill(0x33),
    };
    const otherPool = {
      ...base,
      poolState: new Uint8Array(32).fill(0x44),
    };
    const hash = computeSolanaDomainBoundParamsHash(PARAMS, base);
    expect(computeSolanaDomainBoundParamsHash(PARAMS, otherProgram)).not.toBe(hash);
    expect(computeSolanaDomainBoundParamsHash(PARAMS, otherPool)).not.toBe(hash);
  });

  it("matches the Rust public-domain vector", () => {
    const context = { programId: PROGRAM, poolState: POOL, kind: "public" } as const;
    const separator = bigintTo32Bytes(computeSolanaDomainSeparator(context));
    const bound = bigintTo32Bytes(computeSolanaDomainBoundParamsHash(PARAMS, context));
    const hex = (bytes: Uint8Array) =>
      Array.from(bytes).map((b) => b.toString(16).padStart(2, "0")).join("");

    expect(hex(separator)).toBe("2b76ed47e643d671f5c01988008f8d4012b8abcb14fc937562a56bc957467696");
    expect(hex(bound)).toBe("1f8e124663a84237000a031cbc25f4721756dab3f43d10e78a4ebac49d0c7fdb");
  });

  it("rejects malformed addresses and non-Solana chain IDs", () => {
    expect(() => computeSolanaDomainSeparator({
      programId: new Uint8Array(31),
      poolState: POOL,
      kind: "public",
    })).toThrow("programId must be 32 bytes");
    expect(() => computeSolanaDomainBoundParamsHash(
      createTransferBoundParams(new Uint8Array(32), 999n),
      { programId: PROGRAM, poolState: POOL, kind: "public" },
    )).toThrow("supported Solana chain ID");
    expect(() => computeSolanaDomainSeparator({
      programId: PROGRAM,
      poolState: POOL,
      kind: "partner" as "public",
    })).toThrow("kind must be public or institution");
  });

  it("supports distinct mainnet and devnet domain IDs", () => {
    const context = { programId: PROGRAM, poolState: POOL, kind: "public" } as const;
    const devnet = computeSolanaDomainBoundParamsHash(
      createTransferBoundParams(new Uint8Array(32), 103n),
      context,
    );
    const mainnet = computeSolanaDomainBoundParamsHash(
      createTransferBoundParams(new Uint8Array(32), 101n),
      context,
    );
    expect(mainnet).not.toBe(devnet);
  });
});

describe("computeStealthDataHash", () => {
  it("returns SHA256 of empty for empty array", () => {
    const hash = computeStealthDataHash([]);
    // SHA256("") = e3b0c442...
    expect(hash[0]).toBe(0xe3);
    expect(hash.length).toBe(32);
    // NOT all zeros — must match on-chain sha256(empty_slice)
    expect(hash).not.toEqual(new Uint8Array(32));
  });

  it("produces deterministic output", () => {
    const sd1 = new Uint8Array(72).fill(0xAA);
    const sd2 = new Uint8Array(72).fill(0xBB);
    const hash1 = computeStealthDataHash([sd1, sd2]);
    const hash2 = computeStealthDataHash([sd1, sd2]);
    expect(hash1).toEqual(hash2);
  });

  it("different data produces different hashes", () => {
    const sd1 = new Uint8Array(72).fill(0xAA);
    const sd2 = new Uint8Array(72).fill(0xBB);
    const hashA = computeStealthDataHash([sd1]);
    const hashB = computeStealthDataHash([sd2]);
    expect(hashA).not.toEqual(hashB);
  });
});

describe("boundParamsHash properties", () => {
  const STEALTH = new Uint8Array(32);
  const REQ = new Uint8Array(32).fill(0xDD);

  it("different modes produce different hashes", () => {
    const transfer = computeBoundParamsHash(createTransferBoundParams(STEALTH));
    const unshield = computeBoundParamsHash(
      createUnshieldBoundParams(new Uint8Array(32), STEALTH)
    );
    const redeem = computeBoundParamsHash(
      createRedeemBoundParams(new Uint8Array([0x51, 0x20]), STEALTH, REQ)
    );
    expect(transfer).not.toBe(unshield);
    expect(transfer).not.toBe(redeem);
    expect(unshield).not.toBe(redeem);
  });

  it("different stealth data produces different hashes", () => {
    const stealthA = new Uint8Array(32).fill(0x11);
    const stealthB = new Uint8Array(32).fill(0x22);
    const hashA = computeBoundParamsHash(createTransferBoundParams(stealthA));
    const hashB = computeBoundParamsHash(createTransferBoundParams(stealthB));
    expect(hashA).not.toBe(hashB);
  });

  it("different btcScript produces different redeem hashes", () => {
    const stealth = new Uint8Array(32);
    const scriptA = new Uint8Array([0x51, 0x20, 0xAA]);
    const scriptB = new Uint8Array([0x51, 0x20, 0xBB]);
    const hashA = computeBoundParamsHash(createRedeemBoundParams(scriptA, stealth, REQ));
    const hashB = computeBoundParamsHash(createRedeemBoundParams(scriptB, stealth, REQ));
    expect(hashA).not.toBe(hashB);
  });
});
